### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by Tomas-M** [kozyilmaz/zcash-apple#10]
Hello,
when I run make, it works for about 30 minutes, builds all tools, and then fails with simple one line error, like [build] Error 1

Is there any way I could see logs, or enable debug output? So I could see where is it failing. Thank you

**Comment by kozyilmaz** [comment]
Sure, you can try
`$ PRINT_DEBUG=y make all`

**Comment by Tomas-M** [comment]
Awesome, thank you, maybe this should be documented in the readme. Closing ticket :)

**Comment by kozyilmaz** [comment]
Exactly @Tomas-M, will be closing this issue with that commit.
Are you able to solve it?

**Comment by kozyilmaz** [comment]
Added debug info command to README: https://github.com/kozyilmaz/zcash-apple/commit/70b0ca2b6855093611195e9dd57abb28f96dccaa

**Comment by Tomas-M** [comment]
Yes it works. Thank you!
