### ISSUE TITLE
blockchain sync question and version

### ISSUE THREAD

**Issue by masterdragon69** [kozyilmaz/zcash-apple#11]
Is there a way to speed up the blockchain sync? its terribly slow and im wiating on coin. The commands also did nothing and im running the 0.44 beta any tips?

**Comment by kozyilmaz** [comment]
There is no 0.44 beta release for this project, is it possible that you are mistaken with another zcash project?
In any case [this discussion](https://bitcointalk.org/index.php?topic=2053708.0) suggests using `dbcache` parameter to speed up sync. It is in MB so for a 1GB cache:
`$ zcashd -dbcache=1000`

Let me know if that helps;

**Comment by kozyilmaz** [comment]
@masterdragon69 did `dbcache` option helped? Can I close this?
