### ISSUE TITLE
zcash 1.0.15

### ISSUE THREAD

**Issue by Tomas-M** [kozyilmaz/zcash-apple#15]
Zcash 1.0.15 is released. I think you are in sync with 1.0.15-rc1 already, so making a release for 1.0.15 should be possible, right? Thank you

**Comment by kozyilmaz** [comment]
No problem, released v1.0.15a:
https://github.com/kozyilmaz/zcash-apple/releases/tag/v1.0.15a

**Comment by Tomas-M** [comment]
It worked, I forgot to inform you.
Thank you very much for maintaining this project, it is very useful! :)

**Comment by kozyilmaz** [comment]
@Tomas-M no worries :) glad you are using it!
