### ISSUE TITLE
Build fails after latest commit in master

### ISSUE THREAD

**Issue by rex4539** [kozyilmaz/zcash-apple#17]
Hi @kozyilmaz 

Looks like the latest commit in master broke the build.

Using the `rex4539` branch you created for me.

Hope it's an easy fix :)

```
consensus/upgrades.cpp:72:1: error: control may reach end of non-void function [-Werror,-Wreturn-type]
}
^
1 error generated.
make[5]: *** [consensus/libbitcoin_common_a-upgrades.o] Error 1
```

[build.log](https://github.com/kozyilmaz/zcash-apple/files/1865192/build.log)

**Comment by kozyilmaz** [comment]
@rex4539 sorry for the delay, can you give it a try?
`enable-werror` in build script is causing a lot of trouble for macOS and this is the first one. I removed `enable-werror` but also I'll go over all warnings and submit PR's along the way.

**Comment by rex4539** [comment]
Compiled! Thanks again :)
