### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by yyyfor** [kozyilmaz/zcash-apple#18]
failure logs:

configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 9.1.0, (clang-902.0.39.1) (static support for 21, runtime is 21)
TAPI support using: Apple TAPI version 9.1.0 (tapi-902.0.9)
+ HOST=x86_64-apple-darwin17.5.0
+ BUILD=x86_64-apple-darwin17.5.0
+ NO_RUST=
+ NO_PROTON=--enable-proton=no
+ make -j 4 -C ./depends/ V=1
rm -rf /Users/Ming/Desktop/mining-pool/zcash-apple/zcash/zcash_v1.0.15/depends/x86_64-apple-darwin17.5.0
rm: cannot remove '/Users/Ming/Desktop/mining-pool/zcash-apple/zcash/zcash_v1.0.15/depends/x86_64-apple-darwin17.5.0/include/boost': Directory not empty
make[3]: *** [/Users/Ming/Desktop/mining-pool/zcash-apple/zcash/zcash_v1.0.15/depends/x86_64-apple-darwin17.5.0/.stamp_0ab1e5e20b9] Error 1
make[2]: *** [zcash_build] Error 2
make[1]: *** [build] Error 1
make: *** [zcash_all] Error 2

Someone help please?

**Comment by kozyilmaz** [comment]
@yyyfor weird, it looks like a permission issue. Can you try again with a fresh clone with logs on:
`PRINT_DEBUG=y make all`

**Comment by yyyfor** [comment]
@kozyilmaz Sorry for the late reply. i retried make for several times until it success. Everytime console appears different errors, no idea what was going on but it works now. Thanks

**Comment by kozyilmaz** [comment]
Not at all, feel free to ping me if you have more issues.
