### ISSUE TITLE
Produce precompiled 1.1.0 binary

### ISSUE THREAD

**Issue by rex4539** [kozyilmaz/zcash-apple#19]
https://github.com/zcash/zcash/releases/tag/v1.1.0

1.1.0 has been released.

Please produce a precompiled binary to make it easier for those who are unable to compile locally.

Whenever you have some free time :)

**Comment by kozyilmaz** [comment]
Thanks for the heads up! Released:
https://github.com/kozyilmaz/zcash-apple/releases/tag/v1.1.0a

**Comment by rex4539** [comment]
🥇
