### ISSUE TITLE
Xcode

### ISSUE THREAD

**Issue by food4fort** [kozyilmaz/zcash-apple#2]
Hi kozyilmaz,
Thanks so much for zcash-apple! Seems to be dependent on having Xcode installed. Might be worth mentioning in the dependencies :)
Cheers, Tom

**Comment by kozyilmaz** [comment]
Indeed, https://github.com/kozyilmaz/zcash-apple/commit/11871d20ed74821f3b49bfd1470a3ecfdaad724a fixes that.
Thanks for the heads up!
