### ISSUE TITLE
edge branch fails due to removal of --disable-libs

### ISSUE THREAD

**Issue by rex4539** [kozyilmaz/zcash-apple#20]
Fails because `--disable-libs` has been removed by https://github.com/zcash/zcash/pull/3153

Removing `--disable-libs` from makefile it then fails with:

```
clangclang: : errorerror: : argument unused during compilation: '-pie' [-Werror,-Wunused-command-line-argument]
argument unused during compilation: '-pie' [-Werror,-Wunused-command-line-argument]
```

**Comment by kozyilmaz** [comment]
`edge` branch should work now, tested with https://github.com/zcash/zcash/commit/312f70091bfccb6f61c600bc3b4cb92d6d59e1d8

**Comment by rex4539** [comment]
Compiled :)
