### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by mech314** [kozyilmaz/zcash-apple#22]
Hey, could anyone please help me here?
 CLONE      autoconf
  CONFIG     autoconf
  BUILD      autoconf
  INSTALL    autoconf
  CLONE      automake
  CONFIG     automake
  BUILD      automake
  INSTALL    automake
  CLONE      libtool
  CONFIG     libtool
  BUILD      libtool
  INSTALL    libtool
  CLONE      pkgconfig
  CONFIG     pkgconfig
  BUILD      pkgconfig
  INSTALL    pkgconfig
  CLONE      cmake
  CONFIG     cmake
  BUILD      cmake
  INSTALL    cmake
  CLONE      coreutils
  CONFIG     coreutils
  BUILD      coreutils
  INSTALL    coreutils
  CLONE      zcash
  CONFIG     zcash
  BUILD      zcash
make[1]: *** [build] Error 1
make: *** [zcash_all] Error 2

And here is debug:

This program built for i386-apple-darwin11.3.0
+ eval gcc --version
++ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
+ eval g++ --version
++ g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
+ as --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
+ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-305
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 9.0.0, (clang-900.0.39.2) (static support for 21, runtime is 21)
TAPI support using: Apple TAPI version 900.0.15 (tapi-900.0.15)
+ HOST=x86_64-apple-darwin17.3.0
+ BUILD=x86_64-apple-darwin17.3.0
+ NO_RUST=
+ NO_PROTON=--enable-proton=no
+ make -j 4 -C ./depends/ V=1
echo Preprocessing libevent...
Preprocessing libevent...
mkdir -p /Users/usr/zcash-apple/zcash/zcash_v1.0.15/depends/work/build/x86_64-apple-darwin17.3.0/libevent/2.1.8-b6384ab0b2e /Users/usr/zcash-apple/zcash/zcash_v1.0.15/depends/work/build/x86_64-apple-darwin17.3.0/libevent/2.1.8-b6384ab0b2e/.patches-b6384ab0b2e
cd /Users/usr/zcash-apple/zcash/zcash_v1.0.15/depends/work/build/x86_64-apple-darwin17.3.0/libevent/2.1.8-b6384ab0b2e;   ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autom4te: need GNU m4 1.4 or later: /opt/local/bin/gm4
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
make[3]: *** [/Users/usr/zcash-apple/zcash/zcash_v1.0.15/depends/work/build/x86_64-apple-darwin17.3.0/libevent/2.1.8-b6384ab0b2e/.stamp_preprocessed] Error 1
make[2]: *** [zcash_build] Error 2
make[1]: *** [build] Error 1
make: *** [zcash_all] Error 2

**Comment by kozyilmaz** [comment]
It seems your Zcash version is 1.0.15, so its a bit old. Last tested version is 1.1.0, can you try with the up-to-date zcash-apple with a clean clone.

**Comment by mech314** [comment]
It worked thank you!
One more question, does this wallet download entire zcash block chain?

**Comment by kozyilmaz** [comment]
Sorry for my late response, yes, it does download the entire blockchain and you also have to download the Sprout keys to create z-transactions.

Closing now, please re-open if you have any other issues!
