### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by konstantn** [kozyilmaz/zcash-apple#23]
sorry, I have found a solution

**Comment by kozyilmaz** [comment]
`fetch-params` script can be found inside the release zip file, please run that one.

**Comment by konstantn** [comment]
Please give to me the link to this zip file? I find only 006-zcash-macos-fetch.patch in zcash-apple-master.zip.

**Comment by kozyilmaz** [comment]
Assuming you want a precompiled version, last release (zcash-macos-v1.1.0a.tar.bz2) is below. Please follow all the instructions there:
https://github.com/kozyilmaz/zcash-apple/releases/tag/v1.1.0a


However if you want to compile from scratch, follow build instructions:
https://github.com/kozyilmaz/zcash-apple#build-instructions
and run instructions:
https://github.com/kozyilmaz/zcash-apple#run-instructions

**Comment by konstantn** [comment]
Thank you!

**Comment by konstantn** [comment]
This program will have a graphic cover?

**Comment by kozyilmaz** [comment]
If you are asking about the GUI, no, there is none it is a command line program. This repository started as an effort to upstream macOS support and we are approaching near the end, maybe in the future

**Comment by konstantn** [comment]
I have install vaklinov/zcash-swing-wallet-ui and everything works.

**Comment by kozyilmaz** [comment]
Keep in mind it is deprecated! See the notice below:

SECURITY WARNING: As of January 2018 this software wallet is not actively maintained. It may not operate properly with the upstream core/node implementation and it may contain security and/or other vulnerabilities. It is deprecated and should not be used in production!

**Comment by konstantn** [comment]
That is at the moment this application can't be started? Or he needs to be removed?

**Comment by kozyilmaz** [comment]
I am not sure what the effects would be, it may start and misbehave at another stage, so in general it seems deprecated so I don't recommend it.

**Comment by konstantn** [comment]
Means not necessarily to delete him, and it is enough not to start until it is supported again?

**Comment by kozyilmaz** [comment]
Yes
