### ISSUE TITLE
Add precompiled zcashd 1.1.1 binaries

### ISSUE THREAD

**Issue by rex4539** [kozyilmaz/zcash-apple#24]
https://github.com/zcash/zcash/releases/tag/v1.1.1

Hopefully, this is the last time that it's required as macOS support is almost there. Basically, you just need to remove `--enable-werror` from build.sh and it builds directly from source.

**Comment by kozyilmaz** [comment]
Precompiled v1.1.1 binaries are here: https://github.com/kozyilmaz/zcash-apple/releases/tag/v1.1.1a
