### ISSUE TITLE
testnet-support

### ISSUE THREAD

**Issue by timxor** [kozyilmaz/zcash-apple#25]
add support for zcash testnet. Normally you modify ```zcash.conf``` with 
```
testnet=0
addnode=testnet.z.cash
```
I did that at ```~/Library/Application Support/Zcash/zcash.conf```  then restarted it and it looks like it is still on mainnet.

**Comment by kozyilmaz** [comment]
Hi @tcsiwula, I haven't tried testnet before but but maybe testnet parameter should be "1".
I checked it from here: https://github.com/zcash/zcash/wiki/1.0-User-Guide#configuring-for-testnet

**Comment by timxor** [comment]
Thanks will try that and send a pr once i figure it out :)

On Jun 8, 2018, at 10:44 AM, Kazım Özyılmaz <notifications@github.com> wrote:

Hi @tcsiwula, I haven't tried it myself testnet before but but maybe testnet parameter should be "1".
I checked it from here: https://github.com/zcash/zcash/wiki/1.0-User-Guide#configuring-for-testnet

**Comment by timxor** [comment]
Hello @kozyilmaz , I got it to work and updated the docs for test network support. Pull request is here https://github.com/kozyilmaz/zcash-apple/pull/26

**Comment by kozyilmaz** [comment]
Thanks again, merged!
