### ISSUE TITLE
Can't find output files

### ISSUE THREAD

**Issue by GratefulDave** [kozyilmaz/zcash-apple#28]
I successfully built the Zcash-Apple wallet but do not have a directory out/usr/local/bin on my computer. I have:

Zcash-fetch-params.1 Does the .1 mean that it is for version 1.1?

Zcash-init This is in a completely different directory. 

Zcashhd is nowhere to be found on my computer.

**Comment by GratefulDave** [comment]
And when I do ty to run zcash-fetch-params.1 I get permission denied. I can figure out how to change the permission if required but I do not understand what is going on.

**Comment by kozyilmaz** [comment]
Hi @GratefulDave , there should be a directory named `out` in the top project directory. All the binaries and scripts are inside it, can you verify its there?

**Comment by GratefulDave** [comment]
@kozyilmaz No /out directory. Here is what I have. 
<img width="1043" alt="screen shot 2018-06-30 at 11 37 03 am" src="https://user-images.githubusercontent.com/10969727/42126707-fdd32288-7c59-11e8-9810-44c9e8a734f2.png">

**Comment by kozyilmaz** [comment]
@GratefulDave sorry but it seems `zcash` is not built yet. Is it possible that you run `make all` under `tools` instead of `zcash-apple`?

**Comment by kozyilmaz** [comment]
@GratefulDave may I ask you to try with latest `master` from scratch? I fixed the first issue that you opened in the meantime.

**Comment by GratefulDave** [comment]
@kozyilmaz 

  CLONE      autoconf
  CONFIG     autoconf
  BUILD      autoconf
  INSTALL    autoconf
make -C autoconf-"2.69" install
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-recursive
Making install in bin
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/bin" || ../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/bin"
 /usr/bin/install -c autom4te autoconf autoheader autoreconf ifnames autoscan autoupdate '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/bin'
make[6]: Nothing to be done for `install-data-am'.
Making install in .
make[6]: Nothing to be done for `install-exec-am'.
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf" || build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf"
 /usr/bin/install -c -m 644 ./INSTALL '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf'
Making install in lib
Making install in Autom4te
make[7]: Nothing to be done for `install-exec-am'.
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/Autom4te" || ../../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/Autom4te"
 /usr/bin/install -c -m 644 C4che.pm ChannelDefs.pm Channels.pm Configure_ac.pm FileUtils.pm General.pm Getopt.pm Request.pm XFile.pm '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/Autom4te'
Making install in m4sugar
make[7]: Nothing to be done for `install-exec-am'.
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/m4sugar" || ../../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/m4sugar"
 /usr/bin/install -c -m 644 m4sugar.m4 foreach.m4 m4sh.m4 '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/m4sugar'
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/m4sugar" || ../../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/m4sugar"
 /usr/bin/install -c -m 644 version.m4 m4sugar.m4f m4sh.m4f '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/m4sugar'
Making install in autoconf
make[7]: Nothing to be done for `install-exec-am'.
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autoconf" || ../../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autoconf"
 /usr/bin/install -c -m 644 autoconf.m4 general.m4 status.m4 oldnames.m4 specific.m4 autoheader.m4 autoupdate.m4 autotest.m4 autoscan.m4 lang.m4 c.m4 erlang.m4 fortran.m4 functions.m4 go.m4 headers.m4 types.m4 libs.m4 programs.m4 '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autoconf'
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autoconf" || ../../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autoconf"
 /usr/bin/install -c -m 644 autoconf.m4f '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autoconf'
Making install in autotest
make[7]: Nothing to be done for `install-exec-am'.
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autotest" || ../../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autotest"
 /usr/bin/install -c -m 644 autotest.m4 general.m4 specific.m4 '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autotest'
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autotest" || ../../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autotest"
 /usr/bin/install -c -m 644 autotest.m4f '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autotest'
Making install in autoscan
make[7]: Nothing to be done for `install-exec-am'.
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autoscan" || ../../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autoscan"
 /usr/bin/install -c -m 644 autoscan.list '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf/autoscan'
Making install in emacs
make[7]: Nothing to be done for `install-exec-am'.
 /usr/bin/install -c -m 644 'autoconf-mode.el' '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/emacs/site-lisp/autoconf-mode.el'
 /usr/bin/install -c -m 644 'autoconf-mode.elc' '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/emacs/site-lisp/autoconf-mode.elc'
 /usr/bin/install -c -m 644 'autotest-mode.el' '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/emacs/site-lisp/autotest-mode.el'
 /usr/bin/install -c -m 644 'autotest-mode.elc' '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/emacs/site-lisp/autotest-mode.elc'
make[7]: Nothing to be done for `install-exec-am'.
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf" || ../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf"
 /usr/bin/install -c -m 644 autom4te.cfg '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/autoconf'
Making install in doc
make[6]: Nothing to be done for `install-exec-am'.
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/info" || ../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/info"
 /usr/bin/install -c -m 644 ./autoconf.info ./standards.info '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/info'
 install-info --info-dir='/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/info' '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/info/autoconf.info'
 install-info --info-dir='/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/info' '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/info/standards.info'
Making install in tests
make[6]: Nothing to be done for `install-exec-am'.
make[6]: Nothing to be done for `install-data-am'.
Making install in man
make[6]: Nothing to be done for `install-exec-am'.
test -z "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/man/man1" || ../build-aux/install-sh -c -d "/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/man/man1"
 /usr/bin/install -c -m 644 ./autoconf.1 ./autoheader.1 ./autom4te.1 ./autoreconf.1 ./autoscan.1 ./autoupdate.1 ./ifnames.1 ./config.guess.1 ./config.sub.1 '/Users/david_s_andrews/documents/GitHub/zcash-apple/tools/o/share/man/man1'
  CLONE      automake
  CONFIG     automake
  BUILD      automake
  INSTALL    automake
make -C automake-"1.16.1" install
make: *** automake-1.16.1: No such file or directory.  Stop.
make[2]: *** [automake_install] Error 2
make[1]: *** [install] Error 2
make: *** [automake_all] Error 2

**Comment by kozyilmaz** [comment]
@GratefulDave this build tree does not seem to be clean. Possibly you'll see files like `.cloned`, `.configured` or `.built` in package directories. Can you please do a fresh clone like this and send me the output:
```
Please open a new terminal window
$ git clone https://github.com/kozyilmaz/zcash-apple.git
$ cd zcash-apple
$ source environment
$ PRINT_DEBUG=y make all
```
Sorry for the trouble.

**Comment by GratefulDave** [comment]
Thanks. I needed to install WGET and it worked.  

rpcuser=username
rpcpassword=`head -c 32 /dev/urandom | base64`

The /dev/urandom | base 64 appears to be creating a random password. Is this created the first time the file is run and saved in the config file or does it change each time? It would make more sense for it to remain the same. I just wanted to understand.

Obviously I could use any username . . . .

**Comment by kozyilmaz** [comment]
@GratefulDave `wget` should not be needed, what was the error you encountered? The reason of the existence of this project is being self contained on macOS.

If you followed run instructions (https://github.com/kozyilmaz/zcash-apple#run-instructions) the rpcpassword part is already taken care of by `zcash-init` (created randomly and written to zcash.conf once, used without change afterwards). The part you are quoting is about running the testnet, I will remove that part to eliminate confusion.

**Comment by GratefulDave** [comment]
The error was it required ipfs, wget, or curl. I have curl.

I did the instructions and previously you had:

rpcuser=username
rpcpassword=head -c 32 /dev/urandom | base64

instead of:

rpcuser=SOME_USERNAME
rpcpassword=SOME_PASSWORD

I wanted to understand exactly what is going on because I am very new.

**Comment by GratefulDave** [comment]
And there is no zcash.conf file on my computer except the standard one in examples.

**Comment by kozyilmaz** [comment]
@GratefulDave no worries :)

If you follow the `run instructions` (https://github.com/kozyilmaz/zcash-apple#run-instructions)
```shell
$ cd out/usr/local/bin

# for testnet
$ ./zcash-fetch-params --testnet

# for mainnet
$ ./zcash-fetch-params

$ ./zcash-init
$ ./zcashd
```

The `zcash-init` command that you run once at the installation, actually created a random password for you (see the rpcpassword line) and afterwards you may only run `zcashd`
```
bash-3.2$ cat zcash-init 
#!/bin/bash

# excerpted from zclassic/zutil/init-mac.sh

if [ ! -f "$HOME/Library/Application Support/Zcash/zcash.conf" ]; then
    echo "Creating zcash.conf"
    mkdir -p "$HOME/Library/Application Support/Zcash/"
    echo "rpcuser=zcashrpc" > ~/Library/Application\ Support/Zcash/zcash.conf
    PASSWORD=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    echo "rpcpassword=$PASSWORD" >> "$HOME/Library/Application Support/Zcash/zcash.conf"
    echo "Complete!"
fi
```

**Comment by kozyilmaz** [comment]
@GratefulDave just run the command below on your Terminal to see contents of your `zcash.conf` file, if you didn't follow the `run instructions`please follow them first (you are using mainnet of course). 
```
cat $HOME/Library/Application\ Support/Zcash/zcash.conf
```

**Comment by GratefulDave** [comment]
@kozyilmaz Thank you for being patient with me. I have a few questions:

If I understand correctly testnet is a sandbox and mainnet is the live chain. I did run the testnet first and the mainnet second. I am not sure how that affects the installation. If I am (obviously) not developing and only using mainnet should I just re-initialize with mainnet?

Is it correct to infer that I should only be running mainnet or testnet? In my case mainnet?

**Comment by kozyilmaz** [comment]
@GratefulDave actually you didn't initialize with testnet. By running `./zcash-fetch-params`  and `./zcash-fetch-params --testnet` commands you just downloaded additional data (params) both for mainnet and testnet.

Unless you specifically enabled testnet in your `zcash.conf` like below, you didn't download a single testnet block yet.
```
### connect to test network
testnet=1
addnode=testnet.z.cash
```

And even if you do that, you can safely remove those three lines from your config, restart `zcashd` and Zcash client will connect to mainnet and start syncing without issues don't worry.

**Comment by kozyilmaz** [comment]
Hey @GratefulDave, is everything clear, can I close this issue?
