### ISSUE TITLE
Produce precompiled binaries for 1.1.2

### ISSUE THREAD

**Issue by rex4539** [kozyilmaz/zcash-apple#29]
https://github.com/zcash/zcash/releases/tag/v1.1.2

Thanks!

**Comment by kozyilmaz** [comment]
Like a clock @rex4539. You may find the precompiled Zcash v1.1.2 binaries here:
https://github.com/kozyilmaz/zcash-apple/releases/tag/v1.1.2a

One last pull request is pending (https://github.com/zcash/zcash/pull/3371) after that there will be no Zcash patches for the code itself (but maybe for tools, we'll see)
