### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by minecoins** [kozyilmaz/zcash-apple#3]
Unable to build on Sierra 10.12.6:
...
  CLONE      coreutils
  CONFIG     coreutils
  BUILD      coreutils
  INSTALL    coreutils
  CLONE      gmp
  CONFIG     gmp
  BUILD      gmp
  INSTALL    gmp
  CLONE      mpfr
  CONFIG     mpfr
  BUILD      mpfr
  INSTALL    mpfr
  CLONE      mpc
  CONFIG     mpc
  BUILD      mpc
  INSTALL    mpc
  CLONE      isl
  CONFIG     isl
  BUILD      isl
  INSTALL    isl
  CLONE      gnugcc
  CONFIG     gnugcc
  BUILD      gnugcc
  INSTALL    gnugcc
  CLONE      zcash
  CONFIG     zcash
  BUILD      zcash
make[1]: *** [build] Error 1
make: *** [zcash_all] Error 2

**Comment by kozyilmaz** [comment]
@minecoins Can you run one more time with the command below:
```
PRINT_DEBUG=y make all
```

**Comment by minecoins** [comment]
+ '[' x--disable-libs = x--disable-libs ']'
+ LIBS_ARG=--without-libs
+ shift
++ pwd
+ PREFIX=/Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/x86_64-apple-darwin16.7.0/
+ eval make --version
++ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
+ eval gcc-6.4.0 --version
++ gcc-6.4.0 --version
gcc-6.4.0 (GCC) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ eval g++-6.4.0 --version
++ g++-6.4.0 --version
g++-6.4.0 (GCC) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ as --version
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
+ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-302.3
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 9.0.0, (clang-900.0.37) (static support for 21, runtime is 21)
TAPI support using: Apple TAPI version 900.0.14 (tapi-900.0.14)
+ HOST=x86_64-apple-darwin16.7.0
+ BUILD=x86_64-apple-darwin16.7.0
+ NO_RUST=
+ NO_PROTON=--enable-proton=no
+ make -C ./depends/ V=1
echo Configuring native_ccache...
Configuring native_ccache...
rm -rf /Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/x86_64-apple-darwin16.7.0; mkdir -p /Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/x86_64-apple-darwin16.7.0/lib; cd /Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/x86_64-apple-darwin16.7.0; 
mkdir -p /Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/work/build/x86_64-apple-darwin16.7.0/native_ccache/3.3.1-b72e3afb554/.
cd /Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/work/build/x86_64-apple-darwin16.7.0/native_ccache/3.3.1-b72e3afb554/.;     PKG_CONFIG_LIBDIR=/Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/x86_64-apple-darwin16.7.0/native/lib/pkgconfig PKG_CONFIG_PATH=/Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/x86_64-apple-darwin16.7.0/native/share/pkgconfig PATH=/Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/x86_64-apple-darwin16.7.0/native/bin:/Users/user/git/zcash-apple/tools/o/bin:/Users/user/.cargo/bin:/Users/user/.nvm/versions/node/v6.11.1/bin:/Users/user/.pyenv/shims:/Users/user/.pyenv/bin:/Users/user/.sdkman/candidates/gradle/current/bin:/Users/user/.rbenv/shims:/Users/user/.rbenv/bin:/Users/user/opt/ImageMagick-7.0.1/bin:/Users/user/opt/dex2jar:/Users/user/opt/android-sdk/tools:/Users/user/opt/android-sdk/platform-tools:/Users/user/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/user/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Applications/Wireshark.app/Contents/MacOS   ./configure --host=x86_64-apple-darwin16.7.0 --disable-dependency-tracking --prefix=/Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/x86_64-apple-darwin16.7.0/native         CC="gcc" CXX="g++" NM="nm" RANLIB="ranlib" AR="ar" CPPFLAGS="-I/Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/x86_64-apple-darwin16.7.0/native/include    " LDFLAGS="-L/Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/x86_64-apple-darwin16.7.0/native/lib    "
/bin/sh: Text.app/Contents/SharedSupport/bin:/Users/user/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Applications/Wireshark.app/Contents/MacOS: No such file or directory
make[3]: *** [/Users/user/git/zcash-apple/zcash/zcash_v1.0.12/depends/work/build/x86_64-apple-darwin16.7.0/native_ccache/3.3.1-b72e3afb554/./.stamp_configured] Error 127
make[2]: *** [zcash_build] Error 2
make[1]: *** [build] Error 1
make: *** [zcash_all] Error 2

**Comment by kozyilmaz** [comment]
@minecoins I am not sure but I guess "/Users/user/Applications/Sublime Text.app" is causing trouble because of the "space" in the install path. 
Is it possible for you to remove "Sublime Text" from PKG_CONFIG_PATH just for testing. Or uninstall it just to try?

I'll also try to reproduce it but I may be unreachable for a couple days.

**Comment by minecoins** [comment]
ok, you are right. works by now.

**Comment by kozyilmaz** [comment]
Proposed a patch: https://github.com/zcash/zcash/pull/2700

**Comment by kozyilmaz** [comment]
fixed, upstreamed via https://github.com/zcash/zcash/commit/c720d15c4516012f038d95b9d56cd6c720ad2f20
