### ISSUE TITLE
Tried Again

### ISSUE THREAD

**Issue by GratefulDave** [kozyilmaz/zcash-apple#30]
@kozyilmaz Hi, I tried to reinstall from scratch. It does not create /out directory.

**Comment by kozyilmaz** [comment]
Hi @GratefulDave, can you provide the output logs if you followed the steps?
```
Please open a new terminal window
$ git clone https://github.com/kozyilmaz/zcash-apple.git
$ cd zcash-apple
$ source environment
$ PRINT_DEBUG=y make all
```

**Comment by GratefulDave** [comment]
@kozyilmaz worked perfectly this time. Am I able to randomly change the username and password or are they now immutable?

**Comment by kozyilmaz** [comment]
The username and password (assuming you are talking about the ones in `zcash.conf`) are only to be used for securing RPC calls, thats all. You can change username and password or recreate `zcash.conf` anytime you like. The only thing you have to be careful is if you are using a program using RPC interface to call functions from `zcashd`, correct username and password are needed.

**Comment by GratefulDave** [comment]
@kozyilmaz What's the CLI to turn the node off?

**Comment by kozyilmaz** [comment]
@GratefulDave just re-open the case if you have any questions
