### ISSUE TITLE
zcash.conf settings not taking...

### ISSUE THREAD

**Issue by goofmd** [kozyilmaz/zcash-apple#31]
Newbie alert....

Running zcashd from out/usr/local/bin... and installed zcash.conf with testnet enabled in Application Support/Zcash folder... But - testnet renames disabled despite enabling (and removing #).

So... what are reasons the .conf file isn't being recognized despite comment character being removed for testnet=1?

Output of getmininginfo:

{
  "blocks": 179264,
  "currentblocksize": 0,
  "currentblocktx": 0,
  "difficulty": 5877942.367122299,
  "errors": "",
  "genproclimit": -1,
  "localsolps": 0,
  "networksolps": 307657097,
  "networkhashps": 307657097,
  "pooledtx": 0,
  "testnet": false,
  "chain": "main",
  "generate": false
}

**Comment by andrerfneves** [comment]
Facing similar issue. Seems like the default zcash.conf file is not being taken into account. In the meantime you can run `./zcashd --help` to see all available parameters/flags you can pass. It's essentially the same as the info in your zcash.conf file. There's a `-conf=FILE` param that you can try. Or you can pass the parameters directly on the CLI (which definitely works)

**Comment by goofmd** [comment]
Thanks so much! Will try!

**Comment by kozyilmaz** [comment]
Hi @goofmd  @andrerfneves sorry that it took me so long to respond.
I tried to reproduce the issue but everything seems to work alright. If I add `testnet=1` to zcash.conf in `$HOME/Library/Application\ Support/Zcash/zcash.conf ` like below:

```sh
$ cat $HOME/Library/Application\ Support/Zcash/zcash.conf 
rpcuser=zcashrpc
rpcpassword=DGTWq7T59yYBffjMQgOUyNF6xLfgzplx
#gen=1
testnet=1
```

`zcashd` starts syncing with testnet:
```
$ ./zcash-cli getmininginfo
{
  "blocks": 0,
  "currentblocksize": 0,
  "currentblocktx": 0,
  "difficulty": 1,
  "errors": "",
  "genproclimit": -1,
  "localsolps": 0,
  "networksolps": 0,
  "networkhashps": 0,
  "pooledtx": 0,
  "testnet": true,
  "chain": "test",
  "generate": false
}
```
Anything that I miss?

**Comment by andrerfneves** [comment]
Hmm, not sure @kozyilmaz. Going to try building it in my machine instead of just taking the binaries themselves. I'll report back. Thanks for the response.

**Comment by andrerfneves** [comment]
@kozyilmaz my zcash.conf file was in the incorrect folder. I had the original file at `$HOME/Library/Application\ Support/Zcash/zcash.conf` but was looking at my file at `/Library/Application\ Support/Zcash/zcash.conf`. It's all working great. Go ahead and close this. Cheers

**Comment by kozyilmaz** [comment]
@andrerfneves thanks for the update, closing!
