### ISSUE TITLE
upgrade path to 1.1.0

### ISSUE THREAD

**Issue by zmitton** [kozyilmaz/zcash-apple#32]
My client refuses to run until upgrade 1.1.0 is installed. I pulled the changes, and tried to rebuild however I get this error from `$ PRINT_DEBUG=y make all` : 

```
  INSTALL    automake
make -C automake-"1.16.1" install
make: *** automake-1.16.1: No such file or directory.  Stop.
```
I could do a fresh install but I'm not sure how to save the chain data (so I dont have to sync for another 3 days) and my wallet/keys

**Comment by kozyilmaz** [comment]
Hi @zmitton;

You don't have to worry about chain data (unless you are wiping the machine) as far as I can tell, below are the storage directories. You can just upgrade the `zcashd` daemon version and simply run it.

Here is the stored blockchain
```
$ du -h "$HOME/Library/Application Support/Zcash"
565M	/Users/loki/Library/Application Support/Zcash/blocks/index
 17G	/Users/loki/Library/Application Support/Zcash/blocks
1.0M	/Users/loki/Library/Application Support/Zcash/database
1.1G	/Users/loki/Library/Application Support/Zcash/chainstate
 18G	/Users/loki/Library/Application Support/Zcash
```
Here are the params used in creation of shielded txs
```
$ du -h "$HOME/Library/Application Support/ZcashParams"
880M	/Users/loki/Library/Application Support/ZcashParams
```

I recommend using a precompiled version or doing a clean build (fresh clone and make etc.)
Let me know if you have any issues, hope that helps.

**Comment by kozyilmaz** [comment]
closing
