### ISSUE TITLE
Cannot build (solved)

### ISSUE THREAD

**Issue by pandaiolo** [kozyilmaz/zcash-apple#6]
I could not make it build unless I installed XCode CLI tools by typing:

`xcode-select --install`

After that, it would build with no issue.

Would be a nice addition to the readme :)

Thank for your work on making zcash more available to mac users!

**Comment by kozyilmaz** [comment]
Thanks for the heads up @pandaiolo :)
Updated README accordingly with this commit https://github.com/kozyilmaz/zcash-apple/commit/0874c35f22af9424c515484b25d2499cc6db352e
